Repository openinfradev/kustomize-helm-transformer, pull requests merged in 2020-07, with the labels that each got.

#16 feature: replace $(XXX) pattern to global variable
  examples/helmvalues/site-values.yaml
  plugin/openinfradev.github.com/v1/helmvaluestransformer/HelmValuesTransformer.go
  plugin/openinfradev.github.com/v1/helmvaluestransformer/HelmValuesTransformer_test.go
Labels: enhancement, implement

#19 feature: implementation to replace HelmReleases' chart source
  examples/helmvalues/resources.yaml
  examples/helmvalues/site-values.yaml
  plugin/openinfradev.github.com/v1/helmvaluestransformer/HelmValuesTransformer.go
  plugin/openinfradev.github.com/v1/helmvaluestransformer/HelmValuesTransformer_test.go
Labels: enhancement, implement

#18 add Dockerfile and guide quick start
  Dockerfile
  README.md
Labels: implement

#20 refactor: support map, array types to override chart values
  examples/helmvalues/resources.yaml
  examples/helmvalues/site-values.yaml
  plugin/openinfradev.github.com/v1/helmvaluestransformer/HelmValuesTransformer.go
  plugin/openinfradev.github.com/v1/helmvaluestransformer/HelmValuesTransformer_test.go
Labels: enhancement
